apiVersion: sloth.slok.dev/v1
kind: PrometheusServiceLevel
metadata:
  name: slo-istio-daemon
  namespace: monitoring
  labels:
    release: prometheus
    team: platform-engineering
    env: prod
spec:
  service: "istio"
  labels:
    cluster: "prod-us-east-2"
    component: "kubernetes"
    team: "platform-engineering"
  slos:
    - name: "requests-availability"
      objective: 99.9
      description: "Warn if availability of istio daemon is lower than expected."
      labels:
        category: availability
      sli:
        events:
          errorQuery: sum(rate(istio_requests_total{response_code=~"(5..|429)"}[{{.window}}]))
          totalQuery: sum(rate(istio_requests_total[{{.window}}]))
      alerting:
        name: IstioDaemonAvailabilityAlert
        labels:
          category: "availability"
        annotations:
          summary: "Low availability detected"
        pageAlert:
          labels:
            severity: critical
        ticketAlert:
          labels:
            severity: warning
    - name: "config-change-convergence"
      objective: 99.995
      description: "Warn if Istio config changes pushed to a proxy sidecar converge in less than 0.5 seconds more than 0.005% of the time."
      labels:
        category: convergence
      sli:
        events:
          successQuery: sum(rate(pilot_proxy_convergence_time_bucket{le="0.5"}[{{.window}}]))
          totalQuery: sum(rate(pilot_proxy_convergence_time_count[{{.window}}]))
      alerting:
        name: IstioConfigConvergenceAlert
        labels:
          category: "availability"
        annotations:
          summary: "Low availability detected"
        pageAlert:
          labels:
            severity: critical
        ticketAlert:
          labels:
            severity: warning
