{
 "title": "Istio Monitoring",
 "tags": [
  "PE-Team",
  "Kubernetes",
  "Istio"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Ingress-Gateway Replicas Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"istio-ingressgateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IstioD Replicas Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"istiod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kiali replicas Ready",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_ready{deployment=\"kiali\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}